var search={
  "Activity Instances Collection": "http://fuzzy-sl.squirrel.link/data/Activity_collection",
  "Agent Instances Collection": "http://fuzzy-sl.squirrel.link/data/Agent_collection",
  "Castelcivita Cave": "http://fuzzy-sl.squirrel.link/data/cisite_5",
  "Copecchia": "http://fuzzy-sl.squirrel.link/data/cisite_6",
  "Crvena Stiljena (Montenegro)": "http://fuzzy-sl.squirrel.link/data/cisite_51",
  "Entity Instances Collection": "http://fuzzy-sl.squirrel.link/data/Entity_collection",
  "Franchthi Cave (Greece)": "http://fuzzy-sl.squirrel.link/data/cisite_45",
  "Georeferencing Instances Collection": "http://fuzzy-sl.squirrel.link/data/Georeferencing_collection",
  "Golema Pesht Cave near Zdunje (Macedonia)": "http://fuzzy-sl.squirrel.link/data/cisite_50",
  "Haua-Fteah (Libya)": "http://fuzzy-sl.squirrel.link/data/cisite_65",
  "Kozarnika Cave (Bulgaria)": "http://fuzzy-sl.squirrel.link/data/cisite_42",
  "Lower Danube Basin (Romania)": "http://fuzzy-sl.squirrel.link/data/cisite_55",
  "Marina di Cassano (Naples)": "http://fuzzy-sl.squirrel.link/data/cisite_10",
  "Paglicci Cave": "http://fuzzy-sl.squirrel.link/data/cisite_19",
  "Person Instances Collection": "http://fuzzy-sl.squirrel.link/data/Person_collection",
  "Place Instances Collection": "http://fuzzy-sl.squirrel.link/data/Place_collection",
  "Point Instances Collection": "http://fuzzy-sl.squirrel.link/data/Point_collection",
  "Sant\u2018 Agata dei due Golfi": "http://fuzzy-sl.squirrel.link/data/cisite_27",
  "Sant\u2018 Angelo a Scala": "http://fuzzy-sl.squirrel.link/data/cisite_28",
  "Site Instances Collection": "http://fuzzy-sl.squirrel.link/data/Site_collection",
  "Susak Island (Greece)": "http://fuzzy-sl.squirrel.link/data/cisite_48",
  "Temnata Cave (Bulgaria)": "http://fuzzy-sl.squirrel.link/data/cisite_43",
  "Toplitsa Cave (Bulgaria)": "http://fuzzy-sl.squirrel.link/data/cisite_44",
  "Urluia (Romania)": "http://fuzzy-sl.squirrel.link/data/cisite_52",
  "Vlasca (Romania)": "http://fuzzy-sl.squirrel.link/data/cisite_54"
}